name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Önemli kısım burası!

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with CMake
        run: |
          # 1. Ana dizinde temiz bir 'build' klasörü oluştur
          mkdir -p build
          
          # 2. SDL2'nin kısıtlamasına takılmamak için derlemeyi 'build' klasörünün içinden yönet
          cd build
          
          # 3. CMake'i ana dizine referans vererek çalıştır
          cmake -DBUILD_PRO=ON -DANDROID=ON -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake ..
          
          # 4. Derle
          make
          
          mkdir build && cd build
          cmake -DBUILD_PRO=ON -DANDROID=ON ..
          make
