name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Önemli kısım burası!

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with CMake
        run: |
          mkdir -p build/linux
          cp tic80.desktop.in build/linux/
          # Şimdi ".." yerine dosyanın olduğu yeri (ana dizini) işaret ediyoruz.
          # Eğer CMakeLists.txt ana dizindeyse, komutun sonundaki ".." kısmını "." ile değiştir.
          cmake -DBUILD_PRO=ON -DANDROID=ON -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake .
          make
          
          mkdir build && cd build
          cmake -DBUILD_PRO=ON -DANDROID=ON ..
          make
